#ifndef COLORS_H
#define COLORS_H

#define BACKGROUND_COLOR_DEFAULT    0xFFFFFFF
#define ADDRESS_COLOR_DEFAULT       0xFF5a5a5a
#define HEADER_COLOR_DEFAULT        0xFFaaaa7f
#define COLUMN_COLOR_DEFAULT        0xFF000000
#define ALT_COLUMN_COLOR_DEFAULT    0xFF888888
#define ASCII_COLOR_DEFAULT         0xFF000000

#endif // COLORS_H
