M48
; DRILL file {KiCad 7.0.10} date Sat Apr  6 15:07:33 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-06T15:07:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X4.1545Y-1.0244
X4.3455Y-1.0244
T2
X4.1427Y-0.9051
X4.3573Y-0.9051
T3
X1.14Y-0.99
X1.14Y-2.86
X4.86Y-0.99
X4.86Y-2.86
M30
