name: build

on:
  push:
    branches: [ "master", "develop", "ga-render" ]
  pull_request:
    branches: [ "master", "develop", "ga-render" ]

jobs:
    create-wrl:
      runs-on: ubuntu-latest
      permissions: write-all
      container:
        image: kicad/kicad:8.0.8
      steps:
      - uses: actions/checkout@v3
      - name: Generate wrl
        run: kicad-cli pcb export vrml --output ${{github.workspace}}/board.wrl ${{github.workspace}}/pcb/pico-sst39sf0x0-pcb/pico-sst39sf0x0-pcb.kicad_pcb
      - name: Upload wrl
        uses: actions/upload-artifact@v3
        with:
          name: board.wrl
          path: ${{github.workspace}}/board.wrl
