name: build

on:
  push:
    branches: [ "master", "develop", "ga-render" ]
  pull_request:
    branches: [ "master", "develop", "ga-render" ]

jobs:
    create-wrl:
      runs-on: ubuntu-latest
      permissions: write-all
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Create writable cache directory
          run: mkdir -p ${{ runner.temp }}/kicad_cache
  
        - name: Run KiCad CLI in Docker
          run: |
            docker run --rm \
              -e XDG_CACHE_HOME=${{ runner.temp }}/kicad_cache \
              -v ${{ github.workspace }}:/workspace \
              -w /workspace \
              kicad/kicad:8.0.8 \
              kicad-cli pcb export vrml --output /workspace/board.wrl /workspace/pcb/pico-sst39sf0x0-pcb/pico-sst39sf0x0-pcb.kicad_pcb
