name: build

on:
  push:
    branches: [ "master", "develop", "ga-render" ]
  pull_request:
    branches: [ "master", "develop", "ga-render" ]

jobs:
    create-wrl:
      runs-on: ubuntu-latest
      permissions: write-all
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Create writable cache directory
          run: mkdir -p ${{ runner.temp }}/kicad_cache

        - name: Redirect HOME to a writable directory
          run: mkdir -p ${{ runner.temp }}/home

        - name: Check permissions in GitHub Actions environment
          run: |
            echo "Checking permissions in /home/runner"
            ls -ld /home/runner
            echo "Checking environment variables"
            env
  
        - name: Run KiCad CLI in Docker
          run: |
            docker run --rm \
              --env HOME=/tmp \
              -v ${{ runner.temp }}/home:/home/runner \
              -v ${{ github.workspace }}:/workspace \
              -w /workspace \
              kicad/kicad:8.0.8 \
              ls -la /workspace
            docker run --rm \
              --env HOME=/tmp \
              -v ${{ runner.temp }}/home:/home/runner \
              -v ${{ github.workspace }}:/workspace \
              -w /workspace \
              kicad/kicad:8.0.8 \
              kicad-cli pcb export vrml --output /home/runner/board.wrl /workspace/pcb/pico-sst39sf0x0-pcb/pico-sst39sf0x0-pcb.kicad_pcb
            docker run --rm \
              --env HOME=/tmp \
              -v ${{ runner.temp }}/home:/home/runner \
              -v ${{ github.workspace }}:/workspace \
              -w /workspace \
              kicad/kicad:8.0.8 \
              ls -la /workspace

        - name: Find .wrl files
          run: find ${{ github.workspace }} -name *.wrl
              
        - name: Upload packaging scripts
          uses: actions/upload-artifact@v3
          with:
            name: wrl
            path: ${{ runner.temp }}/board.wrl

    render:
      runs-on: ubuntu-latest
      needs: [create-wrl]
      permissions: write-all
      steps:
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt -y install libpng-dev wget imagemagick
          wget https://master.dl.sourceforge.net/project/castle-engine/rayhunter/rayhunter-1.3.4-linux-x86_64.tar.gz
          tar xzvf rayhunter-1.3.4-linux-x86_64.tar.gz
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: board.wrl
          path: ./
      - name: render
        run: bash scripts/render.sh

