name: build

on:
  push:
    branches: [ "master", "develop", "ga-render" ]
  pull_request:
    branches: [ "master", "develop", "ga-render" ]

jobs:
  render-image:
    name: render-image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: render pcb image
        uses: linalinn/kicad-render@main
        with:
          pcb_file: pcb/pico-sst39sf0x0-pcb/pico-sst39sf0x0-pcb.kicad_pcb
          output_path: ${{ github.workspace }}/images
        
      - name: Upload wrl
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: images/*
